[package]
name = "simple-filesystem"
version = "0.0.1"
authors = ["WangRunji <wangrunji0408@163.com>"]

[dependencies]
bit-set = { default-features = false, version = "0.5" } # default-features contains 'std'
static_assertions = "0.2.5"

[features]
debug_print = []